# Generated by Django 5.2.9 on 2025-12-21 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rol_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_cola', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Escritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ventanilla', models.CharField(max_length=100)),
                ('colas_que_atiende', models.ManyToManyField(related_name='escritorios', to='login.cola')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'pendiente'), ('LLAMANDO', 'llamando'), ('ATENCION', 'atencion'), ('FINALIZADO', 'finalizado'), ('NO_SHOW', 'no se presento')], db_index=True, default='PENDIENTE', max_length=20)),
                ('prioridad', models.CharField(choices=[('NORMAL', 'normal'), ('PREFERENCIAL', 'preferencial'), ('VIP', 'vip')], default='NORMAL', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_llamada', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('cola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.cola')),
                ('escritorio_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to='login.escritorio')),
            ],
        ),
    ]
