# Generated by Django 5.2.9 on 2025-12-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_cola_escritorio_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='nombre_cliente',
            field=models.CharField(blank=True, default='Cliente x', max_length=100, null=True),
        ),
    ]
